Repository dscsmvec/dscsmvec, pull requests merged in 2020-10, with the labels that each got.

#9 changed name in contributing.md
  CONTRIBUTING.md
Labels: hacktoberfest

#10 Changes Applied
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#11 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#12 modified README description
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#13 added license
  LICENSE
Labels: hacktoberfest-accepted
